### ISSUE TITLE
There was an error in the file generated when running with the install command.

### ISSUE THREAD

**Issue by logue** [innocenzi/laravel-vite#279]
There was an error in the file generated when executed with the following command.

```sh
npx @preset/cli apply laravel:inertia
```

* Multiple `\App\Http\Middleware\HandleInertiaRequests::class` are added to`app/Kernel.php`.
* The file name that should be `resources/views/pages/Welcome.vue` was lowercase `welcome.vue`.
* Ziggy setting addition in `app/Http/Middleware/HandleInertiaRequests.php` was invalid.

```php
    public function share(Request $request)
    {
        return array_merge(parent::share($request), [
            'versions' => [
            	'php' => PHP_VERSION,
            	'laravel' => \Illuminate\Foundation\Application::VERSION
            ],
                'user' => $request->user(),
            ],
            'ziggy' => function () {
                return (new Ziggy())->toArray();
            },
        ]);
    }
```

Isn't it correct that it looks like this?

```php
    public function share(Request $request)
    {
        return array_merge(parent::share($request), [
            'versions' => [
            	'php' => PHP_VERSION,
            	'laravel' => \Illuminate\Foundation\Application::VERSION
                'user' => $request->user(),
            ],
            'ziggy' => function () {
                return (new Ziggy())->toArray();
            },
        ]);
    }
```

**Comment by innocenzi** [comment]
I'm guessing you already altered your Laravel project before running the preset. It's meant to be run right after you install Laravel because your changes are not predictable. 

Please read this: https://laravel-vite.dev/guide/extra-topics/inertia.html#conventions
And this: https://laravel-vite.dev/guide/extra-topics/inertia.html#initial-setup

I tested it locally and it work just as expected.
```shell
laravel new project-name
cd project-name
preset apply laravel:vite
```

If you're doing modifications before the last line is ran, it's on you!
