### ISSUE TITLE
Windows clientModule returning null

### ISSUE THREAD

**Issue by bskimball** [innocenzi/laravel-vite#289]
When running vue-stream example on Windows we receive an error:
```
TypeError: Cannot read properties of null (reading 'replace')
```
this comes from the following line in node_modules/fastify-vite/mode/development.js
```
const modulePath = resolve(config.vite.root, config.clientModule.replace(/^\/+/, ''))
```

it looks like the root of the client is returning null. On linux this same app works fine. 

In order to fix this on Windows I changed the root in vite config to a relative path (i.e. "./client"). And in package.json, I change the "build:server" file to "./index.js"

It may be related to this issue https://github.com/nodejs/node/issues/37845

**Comment by innocenzi** [comment]
Hey, `vite-plugin-laravel` doesn't update the `root` property of the Vite configuration. I'm not sure how this issue can be fixed on this end. It seems more like a problem with Vite itself?

If you think something is missing in `vite-plugin-laravel`, feel free to PR. Otherwise I'm not sure how I can help.

**Comment by bskimball** [comment]
Sorry this was meant for fastify-vite wrong repo
