### ISSUE TITLE
Cache manifest in production

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#33]
In order to avoid reading the disk for each request, the manifest should be cached.

I'm not sure if this is actually needed. I don't think Laravel does it for Mix, and the issue would be to remember to clear the cache. Setting an arbitrary TTL is also an option.

Any input on this?

**Comment by georgeboot** [comment]
On larger setups (where there is most gain from performance/efficiency improvements) it would be hardly better to query an external redis/dynamodb/memcached/other than to read from the filesystem.

For small setups, the cache might perhaps be closer, but many small setups use the filesystem driver for cache, so that kind of eliminates any gains.

**Comment by innocenzi** [comment]
Thanks @georgeboot! I'm thinking this is hardly needed as well. 

I'll close for now, but anyone reading this in the future, feel free to reopen if you feel that cache is needed for your use case. :+1:
