### ISSUE TITLE
Development mode does not work.

### ISSUE THREAD

**Issue by Rasool-deldar** [innocenzi/laravel-vite#74]
Everything I do does not work in dev (virtual host -> xampp) mode of the project, it only works in build mode, please help and every time I have to rebuild.

[Example](https://github.com/Rasool-deldar/test-vite)

**Comment by innocenzi** [comment]
Hello, please explain what you mean by "does not work in dev". I can imagine that due to something in your setup, the "detect if dev server is running" feature fails. You can try setting `vite.timeout` to `false` (in `config/vite.php`). 

If that does work, can you tell me what your setup is, so I can try to fix the issue or provide better defaults?

**Comment by Rasool-deldar** [comment]
> Hello, please explain what you mean by "does not work in dev". I can imagine that due to something in your setup, the "detect if dev server is running" feature fails. You can try setting `vite.timeout` to `false` (in `config/vite.php`).
> 
> If that does work, can you tell me what your setup is, so I can try to fix the issue or provide better defaults?

Hi, I noticed that the dev mode is set to port 80 instead of port 3000 and gives a 404 error. Please tell me how to solve this problem.

![image](https://user-images.githubusercontent.com/58503211/116508498-c49ca500-a8d6-11eb-80c9-b9c25e509054.png)

`php
/*
    |--------------------------------------------------------------------------
    | Development URL
    |--------------------------------------------------------------------------
    | The URL at which the Vite development server runs.
    | This is used to generate the script tags when developing.
    */
    'dev_url' => env('APP_URL') . ':3000',
`

`node
export default defineConfig({
  build: {
    manifest: true,
    minify: true,
    sourcemap: true,
    rollupOptions: {
      input: resolve(__dirname, './resources/scripts/main.ts'),
    },
  },
  server: {
    open: false,
    https: false,
    cors: true,
    hmr: {
      host: 'prescription.me',
    },
  },
  resolve: {
    alias: [
      { find: '~', replacement: resolve(__dirname, './resources') },
      { find: '@', replacement: resolve(__dirname, './resources') },
      { find: '@css', replacement: resolve(__dirname, './resources/css') },
      { find: '@scss', replacement: resolve(__dirname, './resources/scss') },
      { find: '@fonts', replacement: resolve(__dirname, './resources/fonts') },
      { find: '@static', replacement: resolve(__dirname, './resources/static') },
      { find: '@js', replacement: resolve(__dirname, './resources/js') },
      { find: '@images', replacement: resolve(__dirname, './resources/static/images') },
      { find: '@scripts', replacement: resolve(__dirname, './resources/scripts') },
      { find: '@components', replacement: resolve(__dirname, './resources/views/components') },
      { find: 'ziggy', replacement: resolve('./vendor/tightenco/ziggy/src/js') },
    ],
  },
  plugins: [
    vue(),
    /*    legacy({
      targets: ['defaults'],
      polyfills: ['es.promise.finally', 'es/map', 'es/set'],
      modernPolyfills: true,
      renderLegacyChunks: true,
    }), */
  ],
  optimizeDeps: {
    include: ['@inertiajs/inertia', '@inertiajs/inertia-vue3'],
  },
});
`

**Comment by innocenzi** [comment]
The issue seems to be your `server.hmr.host` setting. Is there a reason why it is different than `localhost`?

**Comment by Rasool-deldar** [comment]
> The issue seems to be your `server.hmr.host` setting. Is there a reason why it is different than `localhost`?

Hello, do not be bored, it does not work on php artisan serve, the rest of the file works properly, but it does not load fonts and photos.

![image](https://user-images.githubusercontent.com/58503211/116519891-43014300-a8e7-11eb-8a5d-f4c51a2e20fe.png)

![image](https://user-images.githubusercontent.com/58503211/116519909-498fba80-a8e7-11eb-861c-b242a60d55a3.png)

![image](https://user-images.githubusercontent.com/58503211/116519934-51e7f580-a8e7-11eb-8e56-29c09ee72c79.png)

![image](https://user-images.githubusercontent.com/58503211/116520017-6b893d00-a8e7-11eb-886d-e3a76f588097.png)

![image](https://user-images.githubusercontent.com/58503211/116519971-5f04e480-a8e7-11eb-97d8-1d81292fd87b.png)

**Comment by innocenzi** [comment]
This is a different (known) issue: https://github.com/innocenzi/laravel-vite/issues/31

I can't fix it because it requires changes upstream (on Vite's side) to allow back-end integrations to work properly with compiled assets.

I can't think of any solution except not bundling images, fonts etc through Vite right now

**Comment by chuoke** [comment]
Hi, I ran into a similar `404` situation and it took me a while to figure it out. I'll make a hint here in case anyone needs it.

I run the Laravel app in docker, you could be a virtual machine, and I run vite in the host. And this is the crux of the issue.

Before echo vite tags, laravel-vite will check if the manifest should be used to get an entry.  See the [`Vite::shouldUseManifest`](https://github.com/innocenzi/laravel-vite/blob/62e50bee77e4f0706667fa4192bf33b829c1f13d/src/Vite.php#L190) method for detail. In that method will check if the vite server is running, it uses the `fsockopen` function to connect to the vite server. In default config, It can't directly connect to the host in docker, because the base URL is `http://localhost`. So always `false`, that is to say, the manifest should not be used.

My solution is config vite's `dev_url` to host IP for now, such as `http://192.168.0.101:3000`. Maybe you have better ways, remember tell me.

--- 

By the way, @innocenzi , should log `fsockopen` error or throw it out in local env for DX?

**Comment by innocenzi** [comment]
You can disable that feature by setting `ping_timeout` to `null`, or you can configure `ping_url` to specify which URL to ping instead of changing the `dev_url`.

**Comment by rogatty** [comment]
@chuoke you can set `'ping_url' => 'http://host.docker.internal:8080'` if you don't want to hardcode the IP.

If you use Linux then you also need to use `host.docker.internal:host-gateway` map as in https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212
