### ISSUE TITLE
Can't include component without .vue

### ISSUE THREAD

**Issue by atymic** [innocenzi/laravel-vite#96]
Default aliases. 
In component: `import MessageLength from '@/views/components/Component'`

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://localhost:3000/resources/views/Component`

In vite console:
```
Unrestricted file system access to "/resources/views/components/Component"
For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.
```

Fixed by adding.vue, which then breaks phpstorm completion :(

Tried adding this to vite config, which fixed the notice but still cant include.
I guess the error is because vite cant tell what kind of file it is?

Using https://github.com/laravel-presets/inertia
```
server: {
		fs: {
			strict: false,
			allow: ['./']
		}
	}
```

**Comment by innocenzi** [comment]
Hey, this is a Vite-specific [intentional "gotcha"](https://github.com/vitejs/vite/issues/178). This is the same for `.jsx` files, which must end in `.jsx` and not `.js` for instance. 

I can't help you with PHPStorm since I use VSCode and Volar, but I'm kind of surprised that giving the full path breaks the completion. Could it be a configuration option somewhere? Do you use the `tsconfig.json` or did you disable it?

**Comment by atymic** [comment]
Ahh, my bad. 
Managed to get it working with some config overrides, I think the default tsconfig doesn't work for PHPstorm.

**Comment by atymic** [comment]
Thanks for the help :D

**Comment by innocenzi** [comment]
Could you tell me the changes you did to your `tsconfig.json`? Maybe I can update the default from Laravel Vite.
